add_activity:
  name: Add activity
  description: Add an activity to the list.
  fields:
    name:
      name: Name
      description: The name of the item to add (use names field for multiple alternating names).
      required: false  # Changed from true to false
      example: Running
      selector:
        text:
    names:
      name: Names
      description: Multiple names that will cycle each time the activity is completed.
      required: false
      example: ["John's turn", "Mary's turn"]
      selector:
        object:  # This allows for a list of strings
    # At least one of name or names must be provided
    # Other fields remain the same
    category:
      name: Category
      description: The category of the activity.
      required: true
      example: Workout
      selector:
        text:
    frequency:
      name: Frequency
      description: The frequency of the activity
      required: true
      example: 7:0:0
      selector:
        duration:
          enable_day: true
    last_completed:
      name: Last Completed
      description: Last time the activity was done
      required: false
      selector:
        datetime:
    icon:
      name: Icon
      required: false
      selector:
        icon:

remove_name:
  name: Remove Name
  description: Remove a name from an activity's name list.
  fields:
    entity_id:
      name: Entity ID
      description: The id of the entity to update
      required: true
      selector:
        entity:
          filter:
            - integration: "activity_manager"
    index:
      name: Index
      description: The index of the name to remove
      required: true
      selector:
        number:
          min: 0
          mode: box
          
remove_activity:
  name: Remove Activity
  description: Remove the first item with matching name from the list.
  fields:
    entity_id:
      name: Entity ID
      description: The id of the entity to update
      required: true
      example: Workout
      selector:
        entity:
          filter:
            - integration: "activity_manager"

update_activity:
  name: Update Activity
  description: Update the activity
  fields:
    entity_id:
      name: Entity ID
      description: The id of the entity to update
      required: true
      example: Workout
      selector:
        entity:
          filter:
            - integration: "activity_manager"
    now:
      name: Now
      description: Preferred over last completed
      required: false
      selector:
        boolean:
    last_completed:
      name: Last Completed
      description: Last time the activity was done
      required: false
      selector:
        datetime:
    category:
      name: Category
      description: The category
      required: false
      example: Workout
      selector:
        text:
    frequency:
      name: Frequency
      description: The frequency of the activity
      required: false
      example: 07:00:00
      selector:
        duration:
          enable_day: true
    icon:
      name: Icon
      required: false
      selector:
        icon:
